version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        executor:
            name: node/default
        steps:
            - add_ssh_keys:
                fingerprints:
                    - '54:19:54:8f:1d:d3:d7:c3:8c:06:09:c0:b3:36:5e:08'
            - checkout
            - node/with-cache:
                steps:
                    - run: npm install
                    - run: npm run build
                    - run: # git push
                        name: push-github
                        command: |
                            git config --global user.email "782655835@qq.com"
                            git config --global user.name "lq782655835"
                            npm run ghpages
workflows:
    build-and-test:
        jobs:
            - build-and-test:
                filters:
                    branches:
                        only: master
